name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: SSH and Update/Clone Repo, Run Build Script
              run: |
                  ssh -o "StrictHostKeyChecking=no" user@calories.alexose.com "
                  if [ -d ~/calorie-tracker ]; then
                    cd ~/calorie-tracker
                    git pull origin main
                  else
                    git clone https://github.com/alexose/calorie-tracker.git ~/calorie-tracker 
                    cd ~/calorie-tracker
                  fi
                  npm run build
                  "
